#!/bin/bash
# 📋 AMIR BRIDGE INTEGRATION - COMPLETE COMMAND REFERENCE
# This file shows you exactly where each command is located and how to run them
# Author: GitHub Copilot
# Date: August 9, 2025

echo "📋 AMIR BRIDGE INTEGRATION - COMPLETE COMMAND REFERENCE"
echo "=============================================================="
echo "Date: $(date)"
echo "Current Location: $(pwd)"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔍 COMMAND LOCATIONS & DESCRIPTIONS${NC}"
echo "=============================================================="

echo -e "${CYAN}1. TEST SUITE COMMANDS${NC}"
echo "----------------------------------------"
echo "📁 Location: /home/hazem/Miando/"
echo ""
echo "🧪 Complete Test Suite (Python-based, recommended):"
echo "   Command: python3 run_complete_bridge_tests.py"
echo "   File: run_complete_bridge_tests.py"
echo "   Description: Comprehensive Python test suite with detailed output"
echo ""
echo "🧪 Complete Test Suite (Bash-based, alternative):"
echo "   Command: bash run_complete_bridge_tests.sh"
echo "   File: run_complete_bridge_tests.sh"
echo "   Description: Bash version with some string escaping issues"
echo ""

echo -e "${CYAN}2. INDIVIDUAL COMPONENT TESTS${NC}"
echo "----------------------------------------"
echo "📁 Location: /home/hazem/Miando/"
echo ""
echo "🌉 Full Bridge Integration Test:"
echo "   Command: python3 test_amir_bridge_integration.py"
echo "   File: test_amir_bridge_integration.py"
echo "   Description: Tests bridge integration between Amir's data and PostgreSQL"
echo ""
echo "🔄 JSON Split Pattern Compatibility Test:"
echo "   Command: python3 test_json_split_pattern.py"
echo "   File: test_json_split_pattern.py"
echo "   Description: Tests compatibility with JSON Split pattern system"
echo ""

echo -e "${CYAN}3. BRIDGE SYSTEM PRODUCTION COMMANDS${NC}"
echo "----------------------------------------"
echo "📁 Location: /home/hazem/Miando/"
echo ""
echo "🌉 Main Bridge Component:"
echo "   Command: python3 data_bridge.py"
echo "   File: data_bridge.py"
echo "   Description: Main bridge component for data integration"
echo ""
echo "📊 Monitoring Dashboard:"
echo "   Command: python3 monitor.py"
echo "   File: monitor.py"
echo "   Description: Real-time monitoring of bridge system"
echo ""
echo "📈 Status Dashboard:"
echo "   Command: python3 dashboard.py"
echo "   File: dashboard.py"
echo "   Description: System status and health dashboard"
echo ""

echo -e "${CYAN}4. DATABASE VERIFICATION COMMANDS${NC}"
echo "----------------------------------------"
echo "📁 Location: Any terminal with PostgreSQL access"
echo ""
echo "🔍 Test Trading Session Function:"
echo "   Command: psql -h localhost -p 5434 -U amirfund_user -d amirfund_db -c \"SELECT get_trading_session(NOW()::timestamp);\""
echo "   Description: Verify the fixed trading session function"
echo ""
echo "📊 Check Recent OHLC Data:"
echo "   Command: psql -h localhost -p 5434 -U amirfund_user -d amirfund_db -c \"SELECT COUNT(*) FROM ohlc_data WHERE open_time >= NOW() - INTERVAL '24 hours';\""
echo "   Description: Count recent OHLC records from last 24 hours"
echo ""

echo -e "${CYAN}5. JSON SPLIT PATTERN GENERATION${NC}"
echo "----------------------------------------"
echo "📁 Location: /home/hazem/Miando/patterns/json_split/"
echo ""
echo "🔄 Force Fresh Pattern Generation:"
echo "   Command: cd patterns/json_split && python3 force_fresh_pattern.py"
echo "   File: patterns/json_split/force_fresh_pattern.py"
echo "   Description: Generate fresh pattern JSON from latest data"
echo ""
echo "🧪 Test JSON Split Pattern System:"
echo "   Command: cd patterns/json_split && python3 test_pattern_system.py"
echo "   File: patterns/json_split/test_pattern_system.py"
echo "   Description: Test the JSON Split pattern system"
echo ""

echo ""
echo -e "${BLUE}📋 QUICK START GUIDE${NC}"
echo "=============================================================="
echo ""
echo -e "${YELLOW}🚀 To run everything from scratch:${NC}"
echo ""
echo "# 1. Navigate to main directory"
echo "cd /home/hazem/Miando"
echo ""
echo "# 2. Run comprehensive test suite"
echo "python3 run_complete_bridge_tests.py"
echo ""
echo "# 3. If tests pass, start bridge system"
echo "python3 data_bridge.py &        # Start in background"
echo "python3 monitor.py &            # Start monitoring"
echo "python3 dashboard.py            # Run dashboard (foreground)"
echo ""
echo "# 4. Test JSON Split pattern generation"
echo "cd patterns/json_split"
echo "python3 force_fresh_pattern.py"
echo ""

echo ""
echo -e "${BLUE}📂 FILE STRUCTURE SUMMARY${NC}"
echo "=============================================================="
echo ""
echo "/home/hazem/Miando/"
echo "├── 🧪 run_complete_bridge_tests.py     # Main test suite (Python)"
echo "├── 🧪 run_complete_bridge_tests.sh     # Alternative test suite (Bash)"
echo "├── 🌉 data_bridge.py                   # Main bridge component"
echo "├── 📊 monitor.py                       # Monitoring system"
echo "├── 📈 dashboard.py                     # Status dashboard"
echo "├── 🧪 test_amir_bridge_integration.py  # Bridge integration tests"
echo "├── 🔄 test_json_split_pattern.py       # JSON Split compatibility tests"
echo "└── patterns/json_split/"
echo "    ├── 🔄 force_fresh_pattern.py       # Pattern generation"
echo "    ├── 🧪 test_pattern_system.py       # Pattern system tests"
echo "    └── 📄 common.py                    # Database connection utilities"
echo ""

echo ""
echo -e "${GREEN}✅ ALL COMMANDS ARE READY TO USE!${NC}"
echo ""
echo "💡 Tip: Start with 'python3 run_complete_bridge_tests.py' to verify everything works"
echo "🎯 Goal: Bridge Amir's Windows MT5 data → PostgreSQL → JSON Split Pattern System"
echo ""
echo "=============================================================="
echo "Command reference completed at: $(date)"
