target-version = "py311"
line-length = 100
include = [
    "data_bridge.py",
    "monitor.py",
    "patterns/json_split/common.py",
    "patterns/json_split/ohlc_all_live.py",
    "patterns/json_split/pattern_json_live.py",
    "patterns/json_split/pattern_json_history.py",
    "ci_tests/**/*.py",
]

[lint]
select = ["E4", "E7", "E9", "F"]
